version: '3.4'

services:

  igotci_backend:
    container_name: strapi_devtrust
    build:
      context: .
      dockerfile: Dockerfile.prod
      
  postgres:
    container_name: postgres
    image: postgres:14
    command: postgres -c 'max_connections=60'
    restart: always
    tty: true
    env_file: .env_postgres
    #ports:
    #  - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    security_opt:
      - no-new-privileges:true

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:6.14 #:5.7
    env_file: .env_pgadmin
    ports:
      - 8080:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
    tty: true
    security_opt: 
      - no-new-privileges:true
    cpus: 0.5
    mem_limit: 1G

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9001:9000
      #- 8001:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: always
    tty: true
    environment:
      VIRTUAL_HOST: http://localhost:9000
      VIRTUAL_PORT: 9000
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

volumes:
  pgadmin-data:
    name: pgadmin-data
  postgres-volume:
    name: postgres-volume
  portainer-data:
    name: portainer-data